#!/bin/bash

./node_modules/.bin/tsc  --esModuleInterop --outdir dist/app  src/server.ts
./node_modules/.bin/esbuild dist/app/server.js --bundle --platform=node  --minify --outfile=dist/server.js
rm -r dist/app
