version: "1.0.0"
networks:
  ola-network:
services:
  ola-project:
    build: .
    container_name: ola-backend
    ports:
      - 192.168.1.77:8000:8000
    networks:
      - ola-network
    volumes:
      - .:/home/app
  mysql-database:
    image: mysql
    container_name: mysql-database
    networks:
      - ola-network
    environment:
      - MYSQL_ROOT_PASSWORD=1234
