version: "1.0.1"
networks:
  ola-network:
services:
  mysql-database:
    image: mysql
    networks:
      - ola-network
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=ola_project_database
  ola-project:
    working_dir: /home/app
    build: .
    ports:
      - 8000:8000
    networks:
      - ola-network
    volumes:
      - ./src:/home/app/src
      - ./multimedia:/home/app/multimedia
    depends_on:
      - mysql-database
  ola-frontend:
    build:
      context: ./ola-frontend
      dockerfile: ./Dockerfile
    ports:
      - 5173:5173
    volumes:
      - ./ola-frontend/src:/home/app/src
