version: "1.0.2"
networks:
  ola-network:
services:
  mysql-database:
    image: mysql
    networks:
      - ola-network
    environment:
      - MYSQL_ROOT_PASSWORD=1234
  ola-project:
    working_dir: /home/app
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    ports:
      - 8000:8000
    networks:
      - ola-network
    volumes:
      - ./src:/home/app/src
    depends_on:
      - mysql-database
